name: Lint Test Deploy
on: push
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Check linting
        run: npm run lint
      - name: Run test
        run: npm test
      - name: Build 
        run: npm run build
      - name: Deployment
        run: echo "Deploying..."
  